use crate::source::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Fn,
    Pub,
    Pkg,
    Use,
    Return,
    Var,
    Val,
    If,
    Else,
    Loop,
    While,
    For,
    In,
    As,
    Break,
    Continue,
    True,
    False,
    Struct,
    Enum,
    Match,
    Defer,
    Try,
    Trait,
    Impl,
    Type,
    Identifier(String),
    Number(String),
    Character(char),
    String(String),
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Colon,
    Comma,
    Semicolon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Equal,
    Less,
    Greater,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    EqualEqual,
    BangEqual,
    LessEqual,
    GreaterEqual,
    AndAnd,
    OrOr,
    DotDot,
    DotDotEqual,
    FatArrow,
    Underscore,
    Dot,
    /// 指针字段访问 `q->x`（M14）。
    Arrow,
    /// 取址 `&e`（M14，单个 `&`，区别于 `&&`）。
    Amper,
    /// 关联函数调用 `T::func`（M15）。
    ColonColon,
    /// 错误传播 / 可选类型语法糖 `?`（M15）。
    Question,
    Eof,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
